=== bikashgupta787/WSD-Lab/WSD Lab/lab 4/lab4.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="School">        
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Student" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
                            <xs:element name="Student-id" type="xs:integer"/>
							<xs:element name="Student-name" type="xs:string"/>
							<xs:element name="Student-age" type="xs:integer"/>
							<xs:element name="Student-class" type="tno"/>
                            <xs:element name="Student-sec" type="xs:string"/>
							<xs:element name="Student-emailid" type="xs:string"/>
							<xs:element name="Student-phonenum" type="xs:integer"/>
							
						</xs:sequence>
                    </xs:complexType>
                </xs:element>
             </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="tno">
    	<xs:restriction base="xs:integer">
    	<xs:minInclusive value="01"/>
    	<xs:maxExclusive value="12"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== bikashgupta787/WSD-Lab/WSD Lab/lab 4/lab4.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="lab4.xsl"?>
<School xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="lab4.xsd"> 
  <Student>
      <Student-id>1</Student-id>
    <Student-name>Sohail Khan</Student-name>
    <Student-age>16</Student-age>
    <Student-class>10</Student-class>
    <Student-sec>A</Student-sec>
    <Student-emailid>abc@gmail.com</Student-emailid>
    <Student-phonenum>8764321907</Student-phonenum>
  </Student>
  <Student>
    <Student-id>2</Student-id>
  <Student-name>Rita Rathore</Student-name>
  <Student-age>08</Student-age>
  <Student-class>5</Student-class>
  <Student-sec>C</Student-sec>
  <Student-emailid>abc@gmail.com</Student-emailid>
  <Student-phonenum>8764321907</Student-phonenum>
</Student>
<Student>
    <Student-id>3</Student-id>
  <Student-name>Soniya Kalra</Student-name>
  <Student-age>06</Student-age>
  <Student-class>1</Student-class>
  <Student-sec>B</Student-sec>
  <Student-emailid>abc@gmail.com</Student-emailid>
  <Student-phonenum>8764321907</Student-phonenum>
</Student>
<Student>
    <Student-id>4</Student-id>
  <Student-name>Ram Kumar</Student-name>
  <Student-age>13</Student-age>
  <Student-class>07</Student-class>
  <Student-sec>A</Student-sec>
  <Student-emailid>abc@gmail.com</Student-emailid>
  <Student-phonenum>8764321907</Student-phonenum>
</Student>
<Student>
    <Student-id>5</Student-id>
  <Student-name>Virat Singh</Student-name>
  <Student-age>16</Student-age>
  <Student-class>10</Student-class>
  <Student-sec>B</Student-sec>
  <Student-emailid>abc@gmail.com</Student-emailid>
  <Student-phonenum>8764321907</Student-phonenum>
</Student>
<Student>
    <Student-id>6</Student-id>
  <Student-name>Abhinav Iyer</Student-name>
  <Student-age>12</Student-age>
  <Student-class>08</Student-class>
  <Student-sec>A</Student-sec>
  <Student-emailid>abc@gmail.com</Student-emailid>
  <Student-phonenum>8764321907</Student-phonenum>
</Student>
<Student>
    <Student-id>7</Student-id>
  <Student-name>Shruti Jain</Student-name>
  <Student-age>16</Student-age>
  <Student-class>10</Student-class>
  <Student-sec>B</Student-sec>
  <Student-emailid>abc@gmail.com</Student-emailid>
  <Student-phonenum>8764321907</Student-phonenum>
</Student>
<Student>
    <Student-id>8</Student-id>
  <Student-name>Sajal Kumar</Student-name>
  <Student-age>15</Student-age>
  <Student-class>09</Student-class>
  <Student-sec>A</Student-sec>
  <Student-emailid>abc@gmail.com</Student-emailid>
  <Student-phonenum>8764321907</Student-phonenum>
</Student>
</School>
